name: Terraform Auto Apply

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws/terraform
    steps:
    - uses: actions/checkout@v1
    - uses: hashicorp/setup-terraform@v1

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false

    - name: Run test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ICAP_SSH_KEY: ${{ secrets.ICAP_SSH_KEY }}
      run: bash ./tests/test.sh `terraform-bin output -raw icap_server_instance_public_ip | cut -d ':' -f1`
